### ISSUE TITLE
Unable to clone on Windows

### ISSUE THREAD

**Issue by samuelh2005** [DanikingRD/VoxelExperiment#1]
I am unable to clone the repository on Windows. There is an error `error: invalid path 'core/src/net/con.rs'`.

This is because Windows does not support files named `con` because `con` is a reference to the console. See https://superuser.com/questions/86999/why-cant-i-name-a-folder-or-file-con-in-windows for more details.

You could rename the file to `connection.rs` to fix the problem.

**Comment by ldanidev** [comment]
Thanks for letting me know about that one
